### ISSUE TITLE
Cloudformation stucks at Neo4jReplicasTask if we set Replica other than 0

### ISSUE THREAD

**Issue by bkaganyildiz** [getsocial-rnd/neo4j-aws-causal-cluster#3]
Hi @Trane9991 It's me again after I manage to make cluster up and running without any replicas now I've just wanted to add some replicas but after adding replicas using CF, CF fails at Neo4jReplicasTask with status: `Property Environment contains duplicate values.` I guess there's a syntax error with the template. Would you please take a look at it?

**Comment by taraspos** [comment]
@bkaganyildiz thanks for reporting this, checking...

**Comment by taraspos** [comment]
@bkaganyildiz you were right, there was leftover env variable for Read Replica in the template. Should be fixed with the following [commit](https://github.com/getsocial-rnd/neo4j-aws-causal-cluster/commit/9a2a4da2b3db0b7bfc76b7ac92b98954ce5211e7).

PS: I also updated neo4j to the latest 3.5.11 version, you may want to rebuild your docker image.

Thanks!

**Comment by bkaganyildiz** [comment]
Thank you very much 😊
